version: '3'
services:
  app:
    container_name: dockerized-ui-kit
    stdin_open: true
    command:  yarn start
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '9000:9001'
    environment:
      - NODE_ENV=development
      - CI=true
